/*=============================================================
  SRS AI Contracts — Step 5: Anomaly Detection Views
  
  Creates two views:
    1. BILLING_ANOMALIES — joins every billing transaction to its
       matching contract pricing and flags discrepancies.
    2. ANOMALY_SUMMARY — aggregated stats by customer and type.
  
  Requires: 02_create_tables.sql, 03_sample_data.sql
=============================================================*/

USE DATABASE SRS_AI_CONTRACTS;

-- 1. Detailed anomaly view
CREATE OR REPLACE VIEW ANALYTICS.BILLING_ANOMALIES AS
SELECT
    b.TXN_ID,
    b.CUSTOMER_NAME,
    b.TXN_DATE,
    b.SERVICE_TYPE,
    b.TEMPERATURE,
    b.CONTAINER_SIZE,
    b.QUANTITY,
    b.BILLED_UNIT_PRICE,
    b.TOTAL_AMOUNT,
    b.ERP_STATUS,
    cp.CONTRACT_ID,
    cp.UNIT_PRICE AS CONTRACT_UNIT_PRICE,
    cp.VOLUME_TIER_MIN,
    cp.VOLUME_TIER_MAX,
    cp.EFFECTIVE_DATE AS CONTRACT_START,
    cp.EXPIRY_DATE AS CONTRACT_END,
    ROUND(b.BILLED_UNIT_PRICE - cp.UNIT_PRICE, 2) AS PRICE_DIFFERENCE,
    ROUND(((b.BILLED_UNIT_PRICE - cp.UNIT_PRICE) / NULLIF(cp.UNIT_PRICE, 0)) * 100, 2) AS PRICE_VARIANCE_PCT,
    ROUND((b.BILLED_UNIT_PRICE - cp.UNIT_PRICE) * b.QUANTITY, 2) AS REVENUE_IMPACT,
    CASE
        WHEN cp.UNIT_PRICE IS NULL THEN 'NO_CONTRACT_MATCH'
        WHEN ABS(((b.BILLED_UNIT_PRICE - cp.UNIT_PRICE) / NULLIF(cp.UNIT_PRICE, 0)) * 100) <= 1.0 THEN 'WITHIN_TOLERANCE'
        WHEN b.BILLED_UNIT_PRICE > cp.UNIT_PRICE THEN 'OVERCHARGE'
        WHEN b.BILLED_UNIT_PRICE < cp.UNIT_PRICE THEN 'UNDERCHARGE'
    END AS ANOMALY_TYPE
FROM RAW_DATA.BILLING_TRANSACTIONS b
LEFT JOIN RAW_DATA.CONTRACT_PRICING cp
    ON b.CUSTOMER_NAME = cp.CUSTOMER_NAME
    AND b.SERVICE_TYPE = cp.SERVICE_TYPE
    AND b.TEMPERATURE = cp.TEMPERATURE
    AND b.CONTAINER_SIZE = cp.CONTAINER_SIZE
    AND b.QUANTITY >= cp.VOLUME_TIER_MIN
    AND b.QUANTITY <= cp.VOLUME_TIER_MAX
    AND b.TXN_DATE BETWEEN cp.EFFECTIVE_DATE AND cp.EXPIRY_DATE;

-- 2. Summary aggregation view
CREATE OR REPLACE VIEW ANALYTICS.ANOMALY_SUMMARY AS
SELECT
    CUSTOMER_NAME,
    ANOMALY_TYPE,
    COUNT(*) AS TXN_COUNT,
    SUM(TOTAL_AMOUNT) AS TOTAL_BILLED,
    SUM(REVENUE_IMPACT) AS TOTAL_REVENUE_IMPACT,
    AVG(PRICE_VARIANCE_PCT) AS AVG_VARIANCE_PCT,
    MIN(TXN_DATE) AS EARLIEST_TXN,
    MAX(TXN_DATE) AS LATEST_TXN
FROM ANALYTICS.BILLING_ANOMALIES
GROUP BY CUSTOMER_NAME, ANOMALY_TYPE;

/*
  NEXT: Run 06_cortex_search.sql
*/
