/*=============================================================
  SRS AI Contracts — Step 7: Semantic View
  
  Exposes CONTRACT_PRICING and BILLING_ANOMALIES for the Cortex
  Agent's text-to-SQL tool. Includes 6 verified queries that
  teach the agent common SRS billing questions.
  
  Requires: 05_anomaly_views.sql (BILLING_ANOMALIES view must exist)
  
  IMPORTANT: The DDL syntax uses TABLES(), FACTS(), DIMENSIONS(),
  and AI_VERIFIED_QUERIES() — NOT a YAML semantic model.
=============================================================*/

USE DATABASE SRS_AI_CONTRACTS;

CREATE OR REPLACE SEMANTIC VIEW AGENTS.CONTRACTS_SEMANTIC_VIEW
  TABLES (
    SRS_AI_CONTRACTS.RAW_DATA.CONTRACT_PRICING
      COMMENT = 'Structured pricing rules extracted from customer contracts. Contains unit prices by temperature, container size, and volume tier for each customer.',
    SRS_AI_CONTRACTS.ANALYTICS.BILLING_ANOMALIES
      COMMENT = 'Billing transactions joined to contract pricing with anomaly classification. Flags overcharges, undercharges, and no-contract-match situations with revenue impact.'
  )
  FACTS (
    CONTRACT_PRICING.UNIT_PRICE AS UNIT_PRICE,
    CONTRACT_PRICING.VOLUME_TIER_MIN AS VOLUME_TIER_MIN,
    CONTRACT_PRICING.VOLUME_TIER_MAX AS VOLUME_TIER_MAX,
    BILLING_ANOMALIES.BILLED_UNIT_PRICE AS BILLED_UNIT_PRICE,
    BILLING_ANOMALIES.TOTAL_AMOUNT AS TOTAL_AMOUNT,
    BILLING_ANOMALIES.QUANTITY AS QUANTITY,
    BILLING_ANOMALIES.CONTRACT_UNIT_PRICE AS CONTRACT_UNIT_PRICE,
    BILLING_ANOMALIES.PRICE_DIFFERENCE AS PRICE_DIFFERENCE,
    BILLING_ANOMALIES.PRICE_VARIANCE_PCT AS PRICE_VARIANCE_PCT,
    BILLING_ANOMALIES.REVENUE_IMPACT AS REVENUE_IMPACT
  )
  DIMENSIONS (
    CONTRACT_PRICING.CONTRACT_ID AS CONTRACT_ID,
    CONTRACT_PRICING.CUSTOMER_NAME AS CUSTOMER_NAME,
    CONTRACT_PRICING.SERVICE_TYPE AS SERVICE_TYPE,
    CONTRACT_PRICING.TEMPERATURE AS TEMPERATURE,
    CONTRACT_PRICING.CONTAINER_SIZE AS CONTAINER_SIZE,
    CONTRACT_PRICING.EFFECTIVE_DATE AS EFFECTIVE_DATE,
    CONTRACT_PRICING.EXPIRY_DATE AS EXPIRY_DATE,
    CONTRACT_PRICING.EXTRACTION_METHOD AS EXTRACTION_METHOD,
    BILLING_ANOMALIES.TXN_ID AS TXN_ID,
    BILLING_ANOMALIES.CUSTOMER_NAME AS CUSTOMER_NAME,
    BILLING_ANOMALIES.TXN_DATE AS TXN_DATE,
    BILLING_ANOMALIES.SERVICE_TYPE AS SERVICE_TYPE,
    BILLING_ANOMALIES.TEMPERATURE AS TEMPERATURE,
    BILLING_ANOMALIES.CONTAINER_SIZE AS CONTAINER_SIZE,
    BILLING_ANOMALIES.ERP_STATUS AS ERP_STATUS,
    BILLING_ANOMALIES.CONTRACT_ID AS CONTRACT_ID,
    BILLING_ANOMALIES.ANOMALY_TYPE AS ANOMALY_TYPE,
    BILLING_ANOMALIES.CONTRACT_START AS CONTRACT_START,
    BILLING_ANOMALIES.CONTRACT_END AS CONTRACT_END
  )
  COMMENT = 'Semantic view for SRS AI Contracts. Enables natural-language queries about contract pricing, billing anomalies, overcharges, and undercharges across customers, temperatures, and container sizes.'
  AI_VERIFIED_QUERIES (
    '{"question":"Show all billing anomalies for BioPharm Corp","sql":"SELECT TXN_ID, TXN_DATE, TEMPERATURE, CONTAINER_SIZE, QUANTITY, BILLED_UNIT_PRICE, CONTRACT_UNIT_PRICE, PRICE_DIFFERENCE, REVENUE_IMPACT, ANOMALY_TYPE FROM SRS_AI_CONTRACTS.ANALYTICS.BILLING_ANOMALIES WHERE CUSTOMER_NAME = ''BioPharm Corp'' AND ANOMALY_TYPE IN (''OVERCHARGE'', ''UNDERCHARGE'') ORDER BY TXN_DATE","verified_at":"2025-10-01T00:00:00","verified_by":"demo"}',
    '{"question":"What is the total revenue impact of overcharges by customer?","sql":"SELECT CUSTOMER_NAME, COUNT(*) AS OVERCHARGE_COUNT, SUM(REVENUE_IMPACT) AS TOTAL_OVERCHARGE_IMPACT FROM SRS_AI_CONTRACTS.ANALYTICS.BILLING_ANOMALIES WHERE ANOMALY_TYPE = ''OVERCHARGE'' GROUP BY CUSTOMER_NAME ORDER BY TOTAL_OVERCHARGE_IMPACT DESC","verified_at":"2025-10-01T00:00:00","verified_by":"demo"}',
    '{"question":"Show contract pricing for -80C vials across all customers","sql":"SELECT CUSTOMER_NAME, CONTRACT_ID, VOLUME_TIER_MIN, VOLUME_TIER_MAX, UNIT_PRICE, EFFECTIVE_DATE, EXPIRY_DATE FROM SRS_AI_CONTRACTS.RAW_DATA.CONTRACT_PRICING WHERE TEMPERATURE = ''-80C'' AND CONTAINER_SIZE = ''VIAL'' ORDER BY CUSTOMER_NAME, VOLUME_TIER_MIN","verified_at":"2025-10-01T00:00:00","verified_by":"demo"}',
    '{"question":"Compare billed vs contract pricing for all transactions","sql":"SELECT TXN_ID, CUSTOMER_NAME, TEMPERATURE, CONTAINER_SIZE, QUANTITY, BILLED_UNIT_PRICE, CONTRACT_UNIT_PRICE, PRICE_DIFFERENCE, PRICE_VARIANCE_PCT, ANOMALY_TYPE FROM SRS_AI_CONTRACTS.ANALYTICS.BILLING_ANOMALIES ORDER BY ABS(PRICE_VARIANCE_PCT) DESC NULLS LAST","verified_at":"2025-10-01T00:00:00","verified_by":"demo"}',
    '{"question":"What is the anomaly breakdown summary by customer?","sql":"SELECT CUSTOMER_NAME, ANOMALY_TYPE, COUNT(*) AS TXN_COUNT, SUM(REVENUE_IMPACT) AS TOTAL_REVENUE_IMPACT, AVG(PRICE_VARIANCE_PCT) AS AVG_VARIANCE_PCT FROM SRS_AI_CONTRACTS.ANALYTICS.BILLING_ANOMALIES GROUP BY CUSTOMER_NAME, ANOMALY_TYPE ORDER BY CUSTOMER_NAME, ANOMALY_TYPE","verified_at":"2025-10-01T00:00:00","verified_by":"demo"}',
    '{"question":"List all PRE_ERP transactions with overcharges that need review","sql":"SELECT TXN_ID, CUSTOMER_NAME, TXN_DATE, TEMPERATURE, CONTAINER_SIZE, QUANTITY, BILLED_UNIT_PRICE, CONTRACT_UNIT_PRICE, REVENUE_IMPACT FROM SRS_AI_CONTRACTS.ANALYTICS.BILLING_ANOMALIES WHERE ERP_STATUS = ''PRE_ERP'' AND ANOMALY_TYPE = ''OVERCHARGE'' ORDER BY REVENUE_IMPACT DESC","verified_at":"2025-10-01T00:00:00","verified_by":"demo"}'
  );

/*
  NEXT: Run 08_cortex_agent.sql
*/
